language: node_js
sudo: false
node_js:
  - '4'

before_script:
  # Needed to include Chrome in Travis for karma tests
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: 'npm run test-travis'
